trigger: none # will disable CI builds entirely

pr:
  - master

pool:
  vmImage: 'windows-2019'

steps:
  - checkout: self
    clean: true
    lfs: false
    submodules: true
    persistCredentials: false

  - task: CmdLine@2
    displayName: yarn install
    inputs:
      script: yarn install
    condition: 

  - task: DeleteFiles@1
    displayName: Delete webdriver from webdriverio
    inputs:
      SourceFolder: node_modules\webdriverio\node_modules
      Contents: webdriver

  - template: templates/buildTestApp.yml

  - template: templates/deployTestApp.yml

  - task: WinAppDriver.winappdriver-pipelines-task.winappdriver-pipelines-task.Windows Application Driver@0
    displayName: 'Start - WinAppDriver'
    inputs:
      WADArguments: 127.0.0.1 4723/wd/hub
      AgentResolution: 1080p

  - task: CmdLine@2
    displayName: Run WebDriverIO test
    inputs:
      script: yarn run test
      workingDirectory: packages\webdriverio
    condition: succeededOrFailed()

  - task: WinAppDriver.winappdriver-pipelines-task.winappdriver-pipelines-task.Windows Application Driver@0
    displayName: 'Stop - WinAppDriver'
    inputs:
      OperationType: Stop
    condition: succeededOrFailed()

  - task: WinAppDriver.winappdriver-pipelines-task.winappdriver-pipelines-task.Windows Application Driver@0
    displayName: 'Start - WinAppDriver'
    inputs:
      WADArguments: 127.0.0.1 4723/wd/hub
      AgentResolution: 1080p
    condition: succeededOrFailed()

  - task: CmdLine@2
    displayName: yarn install
    inputs:
      script: yarn install
      workingDirectory: packages\selenium-webdriver
    condition: succeededOrFailed()

  - task: CmdLine@2
    displayName: Run selenium-webdriver test
    inputs:
      script: yarn run jest
      workingDirectory: packages\selenium-webdriver
    condition: succeededOrFailed()

  - task: WinAppDriver.winappdriver-pipelines-task.winappdriver-pipelines-task.Windows Application Driver@0
    displayName: 'Stop - WinAppDriver'
    inputs:
      OperationType: Stop
    condition: succeededOrFailed()