trigger: none # will disable CI builds entirely

pr:
  - master

pool:
  vmImage: 'windows-2019'

steps:
  - checkout: self
    clean: true
    lfs: false
    submodules: true
    persistCredentials: false

  - task: PowerShell@2
    displayName: 'Remove WebDriverIO Workaround'
    inputs:
      targetType: 'inline'
      script: '((Get-Content -path packages/webdriverio/package.json -Raw) -replace ".*webdriver.git.*","") | Set-Content -Path packages/webdriverio/package.json'

  - task: CmdLine@2
    displayName: yarn install
    inputs:
      script: yarn install
    condition: 

  - task: PowerShell@2
    displayName: 'Patch WebDriverIO'
    inputs:
      targetType: 'inline'
      script: '((Get-Content -path node_modules/webdriver/build/utils.js -Raw) -replace "if \(!body .*","if (!body) {") | Set-Content -Path node_modules/webdriver/build/utils.js'
  
  - template: templates/buildTestApp.yml

  - template: templates/deployTestApp.yml

  - task: WinAppDriver.winappdriver-pipelines-task.winappdriver-pipelines-task.Windows Application Driver@0
    displayName: 'Start - WinAppDriver'
    inputs:
      WADArguments: 127.0.0.1 4723/wd/hub
      AgentResolution: 1080p

  - task: CmdLine@2
    displayName: Run WebDriverIO test
    inputs:
      script: yarn run test
      workingDirectory: packages\webdriverio
    condition: succeededOrFailed()

  - task: WinAppDriver.winappdriver-pipelines-task.winappdriver-pipelines-task.Windows Application Driver@0
    displayName: 'Stop - WinAppDriver'
    inputs:
      OperationType: Stop
    condition: succeededOrFailed()

  - task: WinAppDriver.winappdriver-pipelines-task.winappdriver-pipelines-task.Windows Application Driver@0
    displayName: 'Start - WinAppDriver'
    inputs:
      WADArguments: 127.0.0.1 4723/wd/hub
      AgentResolution: 1080p
    condition: succeededOrFailed()

  - task: CmdLine@2
    displayName: yarn install
    inputs:
      script: yarn install
      workingDirectory: packages\selenium-webdriver
    condition: succeededOrFailed()

  - task: CmdLine@2
    displayName: Run selenium-webdriver test
    inputs:
      script: yarn run jest
      workingDirectory: packages\selenium-webdriver
    condition: succeededOrFailed()

  - task: WinAppDriver.winappdriver-pipelines-task.winappdriver-pipelines-task.Windows Application Driver@0
    displayName: 'Stop - WinAppDriver'
    inputs:
      OperationType: Stop
    condition: succeededOrFailed()